sudo: false

os:
- linux
#- osx

addons:
  apt_packages:
    - pandoc

#cache:
#  directories:
#  - "$HOME/download/"
#  - "$HOME/install/"

env:
  #- PYTHON_VERSION=2.7
  #- PYTHON_VERSION=3.3
  #- PYTHON_VERSION=3.4
  - PYTHON_VERSION=3.5

env:
  global:
  - ENCRYPTION_LABEL: "$encrypted_a3a89bfc08a4"
  - COMMIT_AUTHOR_EMAIL: "ibinbei@gmail.com"
  
before_install:
- REPO=`git config remote.origin.url`
- SSH_REPO=${REPO/https:\/\/github.com\//git@github.com:}
- SHA=`git rev-parse --verify HEAD`
#- openssl aes-256-cbc -K $encrypted_a3a89bfc08a4_key -iv $encrypted_a3a89bfc08a4_iv -in github_deploy.enc -out github_deploy -d
#- chmod 600 deploy_key
#- eval `ssh-agent -s`
#- ssh-add deploy_key
- wget https://github.com/mzwiessele/travis_scripts/raw/master/download_miniconda.sh
- wget https://github.com/mzwiessele/travis_scripts/raw/master/install_retry.sh
- source download_miniconda.sh
- echo $PATH

install:
- echo $PATH
- source install_retry.sh
- conda install --yes jupyter ipywidgets 
- pip install pypandoc

script:
  - sh run_notebooks.sh
  - git push $SSH_REPO "$TRAVIS_BRANCH"

